# generated by Substrate but won't be overwritten; edit at will

module "atlantis" {
  providers = {
    aws         = aws
    aws.network = aws.network
  }
  source = "../../../../../modules/atlantis/regional"
}
