SET GLOBAL ENFORCE_GTID_CONSISTENCY = ON;
SET @@GLOBAL.GTID_MODE = OFF_PERMISSIVE;
SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;
SET @@GLOBAL.GTID_MODE = ON;
SET @@GLOBAL.SESSION_TRACK_GTIDS = OWN_GTID;
SET @@GLOBAL.SESSION_TRACK_STATE_CHANGE = ON;

USE inventory;
DROP TABLE IF EXISTS employees;
CREATE TABLE employees (
emp_no      INT             NOT NULL,
first_name  VARCHAR(14)     NOT NULL,
last_name   VARCHAR(16)     NOT NULL,
gender      VARCHAR(1)  NOT NULL,
PRIMARY KEY (emp_no)
); 