{
 "title": "Specific Query",
 "description": "Stats to examine a specific query",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "queryfilter", "label": "Query Filter", "query": { "query": "label_values(query)" } }
  ]
 },
 "panels": [
  {
   "title": "Query Text",
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "options": { "content": "${queryfilter}" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Running in Readyset",
   "type": "stat",
   "description": "is this query running in RS or not",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_log_execution_time_count{deployment=\"$deployment\", database_type=\"noria\", query=\"${queryfilter:raw}\", event_type=~\"query|execute\"})"
    },
    {
     "expr": "(query_log_execution_time_count{deployment=\"$deployment\", database_type=\"mysql\", query=\"${queryFilter:raw}\", event_type=~\"query|execute\"})"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "description": "This measures the query end-to-end latency from the time the request is received by ReadySet.",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "query_log_execution_time{quantile=~\"0.5|0.9|0.99\",database_type=\"noria\",deployment=\"$deployment\",query=\"${queryfilter:raw}\"} * 1000",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Total query cache misses rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "query_log_total_cache_misses{deployment=\"$deployment\", query=\"${queryfilter:raw}\"}",
     "legendFormat": "Total misses"
    },
    {
     "expr": "query_log_execution_time_count{deployment=\"$deployment\",database_type=\"noria\",query=\"${queryfilter:raw}\", event_type=~\"query|execute\"}"
    }
   ]
  },
  {
   "title": "Queries Per Second (1 minute intervals)",
   "type": "stat",
   "description": "The number of queries per second executed against ReadySet split by the ReadySet and MySQL backends.",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (database_type) (rate(query_log_execution_time_count{deployment=\"$deployment\", query=\"${queryfilter:raw}\"}[1m]))",
     "legendFormat": "{{database_type}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "description": "The cache hit rate observed at the first layer of ReadySet caches. In the absence of queries this graph shows a cache hit rate of 0%.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(server_view_query_result{deployment=\"$deployment\", result=\"served_from_cache\"}[1m])) / sum(rate(server_view_query_result{result=~\"served_from_cache|replay\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache Eviction Time",
   "type": "timeseries",
   "description": "Cache eviction runs asynchronously in Noria, but can impact the performance of queries that miss at the first layer of caches. This tracks the percent of the last 30 seconds that we spent performing evictions in the cache, reported as the maximum across all caches.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(increase(domain_eviction_time_us_sum{deployment=\"$deployment\"}[30s])) / 3000000"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "sum by (instance, job) ((node_memory_MemTotal_bytes{deployment=\"$deployment\"}-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "System CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 30 },
   "targets": [
    {
     "expr": "100 - (avg by (job, instance) (rate(node_cpu_seconds_total{deployment=\"$deployment\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  }
 ]
}