#!/usr/bin/env bash

set -euo pipefail

if [ -z ${GERRIT_CHANGE_ID+x} ] && [ -z ${GERRIT_PATCHSET+x} ]; then
    echo "Not a CL build, skipping"
    exit 0
fi

msg="Build of patchset $GERRIT_PATCHSET running at $BUILDKITE_BUILD_URL"

body="{
    \"message\": \"$msg\",
    \"omit_duplicate_comments\": true,
    \"ignore_default_attention_set_rules\": true,
    \"reviewers\": [{
        \"reviewer\": \"self\",
        \"notify\": \"NONE\"
    }],
    \"tag\": \"autogenerated:buildkite~running\"
}"

url="https://gerrit.readyset.name/a/changes/$GERRIT_CHANGE_ID/revisions/$GERRIT_PATCHSET/review"

curl \
    -v \
    -X POST \
    --fail-with-body \
    -u "buildkite:$BUILDKITE_GERRIT_PASSWORD" \
    -H "Content-Type: application/json" \
    "$url" \
    -d "$body"
