# generated by Substrate but won't be overwritten; edit at will

module "readyset" {
  providers = {
    aws         = aws
    aws.network = aws.network
  }
  source = "../../../../../modules/sandbox/regional"
}
