use mysql::prelude::FromRow;
use mysql::{FromRowError, Row};

use crate::get;

#[allow(dead_code)]
pub struct InvitesInnerJoinInvitesUser {
    // All columns from `invites`
    id: i64,                                          // int unsigned NOT NULL AUTO_INCREMENT,
    user_id: i64,                                     // int DEFAULT NULL,
    key: String,                 // varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    title: String, // varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    start_date: String, // datetime DEFAULT NULL,
    date: String,  // datetime DEFAULT NULL,
    start_time_set: i64, // tinyint(1) DEFAULT '0',
    end_time_set: i64, // tinyint(1) DEFAULT '0',
    i_type: i64,   // tinyint(1) DEFAULT '1',
    is_deleted: i64, // tinyint(1) DEFAULT '0',
    is_expired: i64, // tinyint(1) DEFAULT '0',
    suggested_invite_id: i64, // int DEFAULT NULL,
    is_default: i64, // tinyint(1) DEFAULT '0',
    show_creator: i64, // tinyint(1) DEFAULT '1',
    latitude: f64, // double(18,12) DEFAULT NULL,
    longitude: f64, // double(18,12) DEFAULT NULL,
    location_name: String, // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    city: String,  // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    state: String, // varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    postal_code: String, // varchar(11) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    address: String, // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    created_at: String, // timestamp NULL DEFAULT NULL,
    updated_at: String, // timestamp NULL DEFAULT NULL,
    chat_tab_updated_at: String, // datetime DEFAULT NULL,
    recurring_type: i64, // tinyint NOT NULL DEFAULT '0',
    image: String, // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    description: String, // text COLLATE utf8mb4_unicode_ci,
    link: String,  // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    is_reported: i64, // tinyint NOT NULL DEFAULT '0',
    parent_invite_id: i64, // int DEFAULT NULL,
    google_calendar_id: i64, // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    google_calendar_recurring_id: i64, // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    is_personal: i64, // tinyint NOT NULL DEFAULT '0',
    is_private: i64, // tinyint(1) NOT NULL DEFAULT '0',
    is_public: i64, // tinyint NOT NULL DEFAULT '0',
    from_google_calendar: i64, // tinyint NOT NULL DEFAULT '0',
    organization_id: i64, // int DEFAULT NULL,
    recurring_invite_id: i64, // int DEFAULT NULL,
    recurring_invite_index: i64, // int DEFAULT NULL,
    is_recurring_invite_template: i64, // tinyint NOT NULL DEFAULT '0',
    is_removed_from_recurring: i64, // tinyint NOT NULL DEFAULT '0',
    is_modified_from_recurring_template: i64, // tinyint NOT NULL DEFAULT '0',
    invitees_can_modify: i64, // tinyint NOT NULL DEFAULT '1',
    initial_start_date: String, // datetime DEFAULT NULL,
    initial_end_date: String, // datetime DEFAULT NULL,
    is_chat_disabled: i64, // tinyint NOT NULL DEFAULT '0',
    are_actions_hidden: i64, // tinyint NOT NULL DEFAULT '0',
    are_people_hidden: i64, // tinyint NOT NULL DEFAULT '0',
    is_creator_hidden: i64, // tinyint NOT NULL DEFAULT '0',
    timezone: String, // varchar(40) COLLATE utf8mb4_unicode_ci DEFAULT 'America/Los_Angeles',
    is_for_followers: i64, // tinyint NOT NULL DEFAULT '0',
    language: String, // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    ticketmaster_min_price_with_fees: f64, // double(8,2) DEFAULT NULL,
    ticketmaster_max_price_with_fees: f64, // double(8,2) DEFAULT NULL,
    ticketmaster_currency: String, // varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    ticketmaster_hot_event: i64, // tinyint DEFAULT '0',
    ticketmaster_onsale_start_datetime: String, // datetime DEFAULT NULL,
    ticketmaster_onsale_end_datetime: String, // datetime DEFAULT NULL,
    ticketmaster_presale_start_datetime: String, // datetime DEFAULT NULL,
    ticketmaster_presale_end_datetime: String, // datetime DEFAULT NULL,
    ticketmaster_min_price: f64, // double(8,2) DEFAULT NULL,
    ticketmaster_max_price: f64, // double(8,2) DEFAULT NULL,
    api_content_provider_id: String, // varchar(155) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    api_content_provider_name: String, // varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    api_content_provider_sort_metric_raw: i64, // bigint DEFAULT NULL,
    api_content_provider_sort_metric_normalized: f64, // double(6,5) DEFAULT NULL,
    can_be_modified: i64, // tinyint NOT NULL DEFAULT '1',
    deeplink: String, // varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    only_creator_can_modify: i64, // tinyint NOT NULL DEFAULT '0',
    is_restricted: i64, // tinyint NOT NULL DEFAULT '0',
    chat_messages_disabled_for_members: i64, // tinyint NOT NULL DEFAULT '0',
    chat_images_disabled_for_members: i64, // tinyint NOT NULL DEFAULT '0',
    chat_polls_disabled_for_members: i64, // tinyint NOT NULL DEFAULT '0',
    // Columns from `invites_users`
    iu_user_id: i64,                  // int DEFAULT NULL,
    iu_invite_id: i64,                // int NOT NULL,
    iu_attending: i64,                // tinyint(1) DEFAULT '0',
    iu_pending: i64,                  // tinyint(1) DEFAULT '0',
    iu_created_at: String,            // timestamp NULL DEFAULT NULL,
    iu_updated_at: String,            // timestamp NULL DEFAULT NULL,
    iu_inviter_id: i64,               // int DEFAULT NULL,
    iu_did_tap_invite: i64,           // tinyint(1) DEFAULT '0',
    iu_did_tap_next_time: i64,        // tinyint(1) DEFAULT '0',
    iu_did_send_seen_notif: i64,      // tinyint(1) DEFAULT '0',
    iu_seen_at: String,               // datetime DEFAULT NULL,
    iu_last_opened_at: String,        // datetime DEFAULT NULL,
    iu_did_opt_out_of_recurring: i64, // tinyint(1) DEFAULT '0',
    iu_removed: i64,                  // tinyint DEFAULT '0',
    iu_interested: i64,               // tinyint NOT NULL DEFAULT '0',
    iu_did_report: i64,               // tinyint NOT NULL DEFAULT '0',
    iu_invited_at: String,            // datetime DEFAULT NULL,
    iu_chat_tab_updated_at: String,   // datetime DEFAULT NULL,
    iu_banned: i64,                   // tinyint NOT NULL DEFAULT '0',
}

impl FromRow for InvitesInnerJoinInvitesUser {
    fn from_row_opt(row: Row) -> Result<Self, FromRowError>
    where
        Self: Sized,
    {
        Ok(InvitesInnerJoinInvitesUser {
            id: get!(row, 0),
            user_id: get!(row, 1),
            key: get!(row, 2),
            title: get!(row, 3),
            start_date: get!(row, 4),
            date: get!(row, 5),
            start_time_set: get!(row, 6),
            end_time_set: get!(row, 7),
            i_type: get!(row, 8),
            is_deleted: get!(row, 9),
            is_expired: get!(row, 10),
            suggested_invite_id: get!(row, 11),
            is_default: get!(row, 12),
            show_creator: get!(row, 13),
            latitude: get!(row, 14),
            longitude: get!(row, 15),
            location_name: get!(row, 16),
            city: get!(row, 17),
            state: get!(row, 18),
            postal_code: get!(row, 19),
            address: get!(row, 20),
            created_at: get!(row, 21),
            updated_at: get!(row, 22),
            chat_tab_updated_at: get!(row, 23),
            recurring_type: get!(row, 24),
            image: get!(row, 25),
            description: get!(row, 26),
            link: get!(row, 27),
            is_reported: get!(row, 28),
            parent_invite_id: get!(row, 29),
            google_calendar_id: get!(row, 30),
            google_calendar_recurring_id: get!(row, 31),
            is_personal: get!(row, 32),
            is_private: get!(row, 33),
            is_public: get!(row, 34),
            from_google_calendar: get!(row, 35),
            organization_id: get!(row, 36),
            recurring_invite_id: get!(row, 37),
            recurring_invite_index: get!(row, 38),
            is_recurring_invite_template: get!(row, 39),
            is_removed_from_recurring: get!(row, 40),
            is_modified_from_recurring_template: get!(row, 41),
            invitees_can_modify: get!(row, 42),
            initial_start_date: get!(row, 43),
            initial_end_date: get!(row, 44),
            is_chat_disabled: get!(row, 45),
            are_actions_hidden: get!(row, 46),
            are_people_hidden: get!(row, 47),
            is_creator_hidden: get!(row, 48),
            timezone: get!(row, 49),
            is_for_followers: get!(row, 50),
            language: get!(row, 51),
            ticketmaster_min_price_with_fees: get!(row, 52),
            ticketmaster_max_price_with_fees: get!(row, 53),
            ticketmaster_currency: get!(row, 54),
            ticketmaster_hot_event: get!(row, 55),
            ticketmaster_onsale_start_datetime: get!(row, 56),
            ticketmaster_onsale_end_datetime: get!(row, 57),
            ticketmaster_presale_start_datetime: get!(row, 58),
            ticketmaster_presale_end_datetime: get!(row, 59),
            ticketmaster_min_price: get!(row, 60),
            ticketmaster_max_price: get!(row, 61),
            api_content_provider_id: get!(row, 62),
            api_content_provider_name: get!(row, 63),
            api_content_provider_sort_metric_raw: get!(row, 64),
            api_content_provider_sort_metric_normalized: get!(row, 65),
            can_be_modified: get!(row, 66),
            deeplink: get!(row, 67),
            only_creator_can_modify: get!(row, 68),
            is_restricted: get!(row, 69),
            chat_messages_disabled_for_members: get!(row, 70),
            chat_images_disabled_for_members: get!(row, 71),
            chat_polls_disabled_for_members: get!(row, 72),
            iu_user_id: get!(row, 73),
            iu_invite_id: get!(row, 74),
            iu_attending: get!(row, 75),
            iu_pending: get!(row, 76),
            iu_created_at: get!(row, 77),
            iu_updated_at: get!(row, 78),
            iu_inviter_id: get!(row, 79),
            iu_did_tap_invite: get!(row, 80),
            iu_did_tap_next_time: get!(row, 81),
            iu_did_send_seen_notif: get!(row, 82),
            iu_seen_at: get!(row, 83),
            iu_last_opened_at: get!(row, 84),
            iu_did_opt_out_of_recurring: get!(row, 85),
            iu_removed: get!(row, 86),
            iu_interested: get!(row, 87),
            iu_did_report: get!(row, 88),
            iu_invited_at: get!(row, 89),
            iu_chat_tab_updated_at: get!(row, 90),
            iu_banned: get!(row, 91),
        })
    }
}
