//! In-place rewriting of recorded query results.
//!
//! `verify --rewrite` re-runs each query against the target database and replaces the recorded
//! result section with the actual results, leaving every other byte of the source file (comments,
//! blank lines, SQL, `error:` tags) untouched. This keeps diffs minimal and preserves provenance
//! comments and Readyset-specific annotations that the parser otherwise discards.

use anyhow::{bail, Result};

use crate::ast::QueryResults;

/// Replace the result block following each `----` separator with the corresponding entry from
/// `new_results`, in query order. All other text is preserved verbatim.
///
/// Each `query` record in a logictest serializes as a block terminated by `----`, followed by its
/// result lines and a blank line (or end of file). `new_results` must contain exactly one entry per
/// such block, in the order they appear.
pub fn substitute_query_results(src: &str, new_results: &[QueryResults]) -> Result<String> {
    let had_trailing_newline = src.ends_with('\n');
    let lines: Vec<&str> = src.lines().collect();
    let mut out: Vec<String> = Vec::with_capacity(lines.len());
    let mut block = 0;

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        out.push(line.to_string());
        i += 1;

        if line == "----" {
            // Skip the original result lines (everything up to the terminating blank line / EOF).
            while i < lines.len() && !lines[i].is_empty() {
                i += 1;
            }

            let results = new_results.get(block).ok_or_else(|| {
                anyhow::anyhow!(
                    "source has more `----` result blocks than supplied results ({})",
                    new_results.len()
                )
            })?;
            let rendered = results.to_string();
            if !rendered.is_empty() {
                out.extend(rendered.split('\n').map(str::to_string));
            }
            block += 1;
        }
    }

    if block != new_results.len() {
        bail!(
            "source has {block} `----` result blocks but {} results were supplied",
            new_results.len()
        );
    }

    let mut result = out.join("\n");
    if had_trailing_newline {
        result.push('\n');
    }
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{QueryResults, Value};

    #[test]
    fn rewrites_hash_count_and_digest_preserving_comments() {
        let src = "\
# Generated by: some command
statement ok
CREATE TABLE t (x INT)

# REA-6472
query I rowsort error: Self-joins unsupported
SELECT x FROM t
----
38 values hashing to 947edd64974ef3dcd87554c3e325298f

";
        let new = vec![QueryResults::Hash {
            count: 40,
            digest: md5::compute("different"),
        }];
        let out = substitute_query_results(src, &new).unwrap();

        // Comments, statement, blank lines, SQL, and the error tag are all preserved.
        assert!(out.contains("# Generated by: some command"));
        assert!(out.contains("# REA-6472"));
        assert!(out.contains("query I rowsort error: Self-joins unsupported"));
        // The old recorded result is replaced by the new one.
        assert!(!out.contains("38 values hashing"));
        assert!(out.contains(&format!(
            "40 values hashing to {:x}",
            md5::compute("different")
        )));
        assert!(out.ends_with('\n'));
    }

    #[test]
    fn rewrites_value_results_block() {
        let src = "\
query I nosort
SELECT x FROM t
----
1
2

";
        let new = vec![QueryResults::Results(vec![
            Value::Integer(7),
            Value::Integer(8),
            Value::Integer(9),
        ])];
        let out = substitute_query_results(src, &new).unwrap();
        assert!(out.contains("\n7\n8\n9\n"));
        assert!(!out.contains("\n1\n2\n"));
    }

    #[test]
    fn errors_when_block_count_mismatches() {
        let src = "query I nosort\nSELECT 1\n----\n1\n\n";
        assert!(substitute_query_results(src, &[]).is_err());
    }
}
