#!/usr/bin/env python3

import json
import os
import sys
import yaml

config = {}
dir_path = os.path.dirname(os.path.realpath(__file__))
with open("%s/../frameworks.yaml" % dir_path) as conf:
    config = yaml.load(conf, Loader=yaml.SafeLoader)["frameworks"]

if os.environ.get("FILTER_FROM_STDIN") != None:
    filter_frameworks = {}
    for f in sys.stdin:
        path = f.strip().split(os.path.sep)
        if len(path) < 4:
            continue
        if path[1] != "frameworks":
            continue
        filter_frameworks[os.path.join(path[2], path[3])] = None
    for (dialect, frameworks) in config.items():
        config[dialect] = list(filter(lambda f: f['name'] in filter_frameworks, frameworks))

print(json.dumps(config, indent=4))
