{
 "title": "Specific Query",
 "description": "Stats to examine a specific query",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "queryfilter", "label": "Query Filter", "query": { "query": "label_values(query)" } }
  ]
 },
 "panels": [
  {
   "title": "Query Text",
   "type": "text",
   "gridPos": { "h": 3, "w": 16, "x": 0, "y": 0 },
   "options": { "content": "${queryfilter}" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Running in Readyset",
   "type": "stat",
   "description": "is this query running in RS or not",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(query_log_execution_time_count{deployment=\"$deployment\", database_type=\"noria\", query=\"${queryfilter:raw}\", event_type=~\"query|execute\"})"
    },
    {
     "expr": "(query_log_execution_time_count{deployment=\"$deployment\", database_type=\"mysql\", query=\"${queryFilter:raw}\", event_type=~\"query|execute\"})"
    }
   ]
  },
  {
   "title": "50p Query Latency",
   "type": "timeseries",
   "description": "This measures the query end-to-end latency from the time the request is received by ReadySet.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "query_log_execution_time{quantile=~\"0.5\",database_type=\"noria\",deployment=\"$deployment\",query=\"${queryfilter:raw}\"} * 1000",
     "legendFormat": "readyset 50p"
    },
    {
     "expr": "query_log_execution_time{quantile=~\"0.5\",database_type=\"mysql\",deployment=\"$deployment\",query=\"${queryfilter:raw}\"} * 1000",
     "legendFormat": "mysql 50p"
    }
   ]
  },
  {
   "title": "90p Query Latency",
   "type": "timeseries",
   "description": "This measures the query end-to-end latency from the time the request is received by ReadySet.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "query_log_execution_time{quantile=~\"0.9\",database_type=\"noria\",deployment=\"$deployment\",query=\"${queryfilter:raw}\"} * 1000",
     "legendFormat": "ReadySet 90p"
    },
    {
     "expr": "query_log_execution_time{quantile=~\"0.9\",database_type=\"mysql\",deployment=\"$deployment\",query=\"${queryfilter:raw}\"} * 1000",
     "legendFormat": "MySQL 90p"
    }
   ]
  },
  {
   "title": "99p Query Latency",
   "type": "timeseries",
   "description": "This measures the query end-to-end latency from the time the request is received by ReadySet.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "query_log_execution_time{quantile=~\"0.99\",database_type=\"noria\",deployment=\"$deployment\",query=\"${queryfilter:raw}\"} * 1000",
     "legendFormat": "ReadySet 99p"
    },
    {
     "expr": "query_log_execution_time{quantile=~\"0.99\",database_type=\"mysql\",deployment=\"$deployment\",query=\"${queryfilter:raw}\"} * 1000",
     "legendFormat": "MySQL 99p"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "query_log_total_cache_misses{deployment=\"$deployment\", query=\"${queryfilter:raw}\"}",
     "legendFormat": "Total misses"
    },
    {
     "expr": "query_log_execution_time_count{deployment=\"$deployment\",database_type=\"noria\",query=\"${queryfilter:raw}\", event_type=~\"query|execute\"}",
     "legendFormat": "Total count"
    }
   ]
  },
  {
   "title": "Queries Per Second (1 minute intervals)",
   "type": "stat",
   "description": "The number of queries per second executed against ReadySet split by the ReadySet and MySQL backends.",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (database_type) (rate(query_log_execution_time_count{deployment=\"$deployment\", query=\"${queryfilter:raw}\"}[1m]))",
     "legendFormat": "{{database_type}}"
    }
   ]
  }
 ]
}