{
 "title": "ReadySet Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": { "query": "label_values(deployment)" } }
  ]
 },
 "panels": [
  { "title": "Did ReadySet start?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ReadySet Started",
   "type": "stat",
   "description": "Time since the server started",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "startup_timestamp" }
   ]
  },
  {
   "title": "Is ReadySet receiving requests?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "ReadySet Client Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(noria_client_external_requests[1m])",
     "legendFormat": "Rate of requests"
    }
   ]
  },
  {
   "title": "ReadySet Client Connections",
   "type": "stat",
   "description": "The number of connections from external client applications to ReadySet.",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "noria_client_connected_clients" }
   ]
  },
  {
   "title": "ReadySet Server Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "increase(server_external_requests[1m])",
     "legendFormat": "Rate of requests"
    }
   ]
  },
  { "title": "Ongoing ReadySet Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Snapshot In Progress",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(replicator_snapshot_status{deployment=\"$deployment\", status=\"started\"}) - sum(replicator_snapshot_status{deployment=\"$deployment\", status=~\"successful|failed\"})"
    }
   ]
  },
  {
   "title": "Migration in Progress",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_migration_in_progress{deployment=\"$deployment\"}"
    }
   ]
  }
 ]
}