{
 "title": "ReadySet Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Deployment", "query": { "query": "label_values(deployment)" } },
   { "name": "QueryFilter", "label": "Query Filter", "query": { "query": "label_values(query)" } }
  ]
 },
 "panels": [
  {
   "title": "Queries Per Second (1 minute intervals)",
   "type": "stat",
   "description": "The number of queries per second executed against ReadySet split by the ReadySet and MySQL backends.",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (database_type) (rate(query_log_execution_time_count{deployment=\"$Deployment\"}[1m]))",
     "legendFormat": "{{database_type}}"
    }
   ]
  },
  {
   "title": "Snapshot In Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(replicator_snapshot_status{deployment=\"$Deployment\", status=\"started\"}) - sum(replicator_snapshot_status{deployment=\"$Deployment\", status=~\"successful|failed\"})"
    }
   ]
  },
  {
   "title": "Migration in Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_migration_in_progress{deployment=\"$Deployment\"}"
    }
   ]
  },
  {
   "title": "ReadySet Adapters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{deployment=\"$Deployment\",job=\"readyset-adapter\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "ReadySet Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{deployment=\"$Deployment\",job=\"readyset-server\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "table",
   "description": "The end-to-end read latencies of queries executed against the ReadySet and MySQL backends at the median, 50th and 90th percentiles.",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (query) (query_log_execution_time{deployment=\"$Deployment\",database_type=\"noria\",query!=\"\", quantile=\"0.5\", event_type=~\"query|execute\"}) *1000"
    },
    {
     "expr": "avg by (query) (query_log_execution_time{deployment=\"$Deployment\",database_type=\"noria\",query!=\"\", quantile=\"0.9\", event_type=~\"query|execute\"}) *1000  "
    },
    {
     "expr": "avg by (query) (query_log_execution_time{deployment=\"$Deployment\",database_type=\"noria\",query!=\"\", quantile=\"0.99\", event_type=~\"query|execute\"}) *1000"
    },
    {
     "expr": "sum by (query) (query_log_execution_time_count{deployment=\"$Deployment\",database_type=\"noria\",query!=\"\", event_type=~\"query|execute\"})"
    },
    {
     "expr": "sum by (query) (query_log_execution_time_count{deployment=\"$Deployment\",database_type=\"postgres\",query!=\"\", event_type=~\"query|execute\"})"
    }
   ]
  },
  {
   "title": "System CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "100 - (avg by (job, instance) (rate(node_cpu_seconds_total{deployment=\"$Deployment\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "description": "This measures the query end-to-end latency from the time the request is received by ReadySet.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "query_log_execution_time{quantile=~\"0.5|0.9|0.99\",database_type=\"noria\",deployment=\"$Deployment\",query=\"${QueryFilter:raw}\"} * 1000",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "description": "The cache hit rate observed at the first layer of ReadySet caches. In the absence of queries this graph shows a cache hit rate of 0%.",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(server_view_query_result{deployment=\"$Deployment\", result=\"served_from_cache\"}[1m])) / sum(rate(server_view_query_result{result=~\"served_from_cache|replay\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache Eviction Time",
   "type": "timeseries",
   "description": "Cache eviction runs asynchronously in Noria, but can impact the performance of queries that miss at the first layer of caches. This tracks the percent of the last 30 seconds that we spent performing evictions in the cache, reported as the maximum across all caches.",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(increase(domain_eviction_time_us_sum{deployment=\"$Deployment\"}[30s])) / 3000000"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 16 },
   "targets": [
    {
     "expr": "sum by (instance, job) ((node_memory_MemTotal_bytes{deployment=\"$Deployment\"}-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  }
 ]
}