# generated by Substrate but won't be overwritten; edit at will

module "readyset" {
  source = "../../../../../modules/sandbox/global"

  providers = {
    aws           = aws
    aws.us-east-1 = aws.us-east-1
  }
}
