#!/bin/bash
set -eo pipefail

echo '--- :git: Cloning nom-sql'
(
    if [ !  -d nom-sql ]; then
        git clone git@github.com:readysettech/nom-sql.git
    fi
    cd nom-sql
    git fetch -v --prune -- origin master
    git checkout -f FETCH_HEAD
    git clean -ffxdq
)
