# generated by Substrate but won't be overwritten; edit at will

module "readyset" {
  providers = {
    aws           = aws
    aws.us-east-1 = aws.us-east-1
  }
  source = "../../../../../modules/readyset/global"
}
