{
 "title": "ReadySet Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries Per Second (1 minute intervals)",
   "type": "stat",
   "description": "The number of queries per second executed against ReadySet split by the ReadySet and MySQL backends.",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (database_type) (rate(query_log_execution_time_count[1m]))",
     "legendFormat": "{{database_type}}"
    }
   ]
  },
  {
   "title": "ReadySet Adapters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{job=\"readyset-adapter\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "ReadySet Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{job=\"readyset-server\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "table",
   "description": "The end-to-end read latencies of queries executed against the ReadySet and MySQL backends at the median, 50th and 90th percentiles.",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"noria\",query!=\"\", quantile=\"0.5\"}) *1000"
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"mysql\",query!=\"\", quantile=\"0.5\"}) *1000 "
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"noria\",query!=\"\", quantile=\"0.9\"}) *1000  "
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"mysql\",query!=\"\", quantile=\"0.9\"}) *1000 "
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"noria\",query!=\"\", quantile=\"0.99\"}) *1000"
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"mysql\",query!=\"\", quantile=\"0.99\"}) *1000"
    }
   ]
  },
  {
   "title": "System CPU Utilization",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (job, instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "ReadySet Server Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max ((node_memory_MemTotal_bytes{job=\"readyset-server\"}-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100)",
     "legendFormat": "Max"
    },
    {
     "expr": "avg ((node_memory_MemTotal_bytes{job=\"readyset-server\"}-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100)",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "ReadySet State Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (domain_total_node_state_size_bytes)",
     "legendFormat": "Dataflow Usage"
    },
    {
     "expr": "sum (node_memory_MemTotal_bytes{job=\"readyset-server\"} - node_memory_MemAvailable_bytes)",
     "legendFormat": "Server Total Usage"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "sum by (instance, job) ((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  }
 ]
}