{
 "title": "ReadySet Overview 2",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ReadySet Read End-to-End Latency",
   "type": "timeseries",
   "description": "The amount of time performing a read query against ReadySet.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (quantile) (noria_client_execution_time{query_type=\"read\", quantile=~\"0.5|0.9|0.99\"}*.001)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "ReadySet+MySQL write latency",
   "type": "timeseries",
   "description": "The end-to-end latency of a write query; the amount of time from when a write was sent from the adapter to MySQL until the write was confirmed and returned to the client.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (quantile) (noria_client_execution_time{query_type=\"write\", quantile=~\"0.5|0.9|0.99\"}*.001)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "ReadySet Adapters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{job=\"readyset-adapter\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "ReadySet Servers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_memory_MemTotal_bytes{job=\"readyset-server\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Queries Executed",
   "type": "table",
   "description": "The count of each type of query executed against ReadySet.",
   "gridPos": { "h": 13, "w": 6, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (query) (query_log_execution_time_count)"
    }
   ]
  },
  {
   "title": "Queries Per Second (1 minute intervals)",
   "type": "stat",
   "description": "The number of queries per second executed against ReadySet split by the ReadySet and MySQL backends.",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (database_type) (rate(query_log_execution_time_count[1m])) * 60",
     "legendFormat": "{{database_type}}"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "table",
   "description": "The end-to-end read latencies of queries executed against the ReadySet and MySQL backends at the median, 50th and 90th percentiles.",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"noria\",query!=\"\", quantile=\"0.5\"})"
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"mysql\",query!=\"\", quantile=\"0.5\"})"
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"noria\",query!=\"\", quantile=\"0.9\"})"
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"mysql\",query!=\"\", quantile=\"0.9\"})"
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"noria\",query!=\"\", quantile=\"0.99\"})"
    },
    {
     "expr": "avg without (quantile,database_type) (query_log_execution_time{database_type=\"mysql\",query!=\"\", quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "System Memory Utilization",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (instance, job) ((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes*100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "System CPU Utilization",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "100 - (avg by (job, instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  }
 ]
}